import { Component, inject, signal } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { firstValueFrom } from 'rxjs';

interface TimelineEvent { date: string; event: string; label: string }
interface OutreachEntry {
  id: string; name: string | null; firm: string | null; category: string;
  status: string; first_contacted: string | null; last_update: string | null;
  touches: number; replied: boolean; public_note: string | null; timeline: TimelineEvent[];
}
interface OutreachLog {
  generated: string; note: string;
  totals: { contacted: number; replied: number; interested: number; in_pipeline: number };
  entries: OutreachEntry[];
}

@Component({
  selector: 'app-outreach',
  template: `
    <section class="hero card">
      <h2>Outreach — in the open</h2>
      <p class="muted">
        We do investor &amp; collaborator outreach <strong>transparently</strong>: this is the live,
        privacy-redacted log of who we've contacted and what came back. Same rule as the rest of the
        project — <strong>the counts are real and re-verifiable.</strong> Names appear only with
        consent; <strong>no email addresses or message contents are ever published.</strong>
      </p>
    </section>

    @if (log(); as l) {
      <div class="stats">
        <div class="stat card"><div class="n">{{ l.totals.in_pipeline }}</div><div class="muted">in pipeline</div></div>
        <div class="stat card"><div class="n">{{ l.totals.contacted }}</div><div class="muted">contacted</div></div>
        <div class="stat card"><div class="n">{{ l.totals.replied }}</div><div class="muted">replied</div></div>
        <div class="stat card"><div class="n">{{ l.totals.interested }}</div><div class="muted">interested</div></div>
      </div>

      @if (l.entries.length) {
        <h3 class="sec-h">Log <span class="muted">— updated {{ l.generated }}</span></h3>
        <div class="rows">
          @for (e of l.entries; track e.id) {
            <div class="card row">
              <div class="who">
                <strong>{{ e.name || e.id }}</strong>
                @if (e.firm) { <span class="muted"> · {{ e.firm }}</span> }
                <span class="pill">{{ e.category }}</span>
                <span class="pill" [class.good]="e.replied">{{ e.status }}</span>
              </div>
              @if (e.public_note) { <p class="note">{{ e.public_note }}</p> }
              <div class="tl">
                @for (t of e.timeline; track $index) {
                  <span class="ev" [class.reply]="t.event === 'reply'">
                    {{ t.date }} · {{ t.event }}@if (t.label) { <em> ({{ t.label }})</em> }
                  </span>
                }
              </div>
              <div class="muted meta">{{ e.touches }} touch(es) · last {{ e.last_update }}</div>
            </div>
          }
        </div>
      } @else {
        <p class="muted empty">No outreach has reached the send stage yet. When it does, every
        contact and follow-up shows up here automatically (redacted) — updated {{ l.generated }}.</p>
      }
    } @else {
      <p class="muted">Loading outreach log…</p>
    }

    <p class="muted foot">
      Generated by the agentic outreach system (<code>outreach/</code>) and committed to the public
      repo so anyone can audit our process. Private data (contacts, message bodies, secrets) is never
      committed — only this redacted summary.
    </p>
  `,
  styles: [`
    .hero { margin-bottom: 1.2rem; }
    .hero h2 { margin-top: 0; }
    .hero p { max-width: 80ch; }
    .stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(120px, 1fr)); gap: 0.6rem; margin-bottom: 1.2rem; }
    .stat { text-align: center; }
    .stat .n { font-size: 1.8rem; font-weight: 700; color: var(--accent); }
    .sec-h { margin: 1.2rem 0 0.7rem; }
    .rows { display: grid; gap: 0.6rem; }
    .row { display: grid; gap: 0.4rem; }
    .who { display: flex; align-items: center; gap: 0.4rem; flex-wrap: wrap; }
    .pill { font-size: 0.72rem; padding: 0.1rem 0.5rem; border-radius: 999px; border: 1px solid var(--border, #2a3b34); }
    .pill.good { color: var(--accent); border-color: var(--accent); }
    .note { font-size: 0.88rem; margin: 0.2rem 0; }
    .tl { display: flex; flex-wrap: wrap; gap: 0.4rem; }
    .ev { font-size: 0.78rem; color: var(--text-dim); border-left: 2px solid var(--border, #2a3b34); padding-left: 0.4rem; }
    .ev.reply { border-left-color: var(--accent); }
    .ev em { color: var(--accent); font-style: normal; }
    .meta { font-size: 0.78rem; }
    .empty { padding: 1rem 0; }
    .foot { font-size: 0.78rem; margin-top: 1.4rem; max-width: 80ch; }
  `],
})
export class Outreach {
  private http = inject(HttpClient);
  readonly log = signal<OutreachLog | null>(null);

  constructor() {
    firstValueFrom(this.http.get<OutreachLog>('data/outreach/log.json'))
      .then((l) => this.log.set(l))
      .catch(() => this.log.set({
        generated: '', note: '',
        totals: { contacted: 0, replied: 0, interested: 0, in_pipeline: 0 }, entries: [],
      }));
  }
}
