export interface MethodStage {
  id: string;
  title: string;
  what: string;
  dataSource: string;
  caveat: string;
}

// Verified methodology copy (generated from the content workflow).
export const METHODS: MethodStage[] = [
  { id: "target-dossier", title: "Target dossier", what: "Resolves your gene or protein name to a single human ChEMBL target and UniProt entry, then summarizes its molecular function, sequence length, count of potent bioactivity records, cross-referenced PDB structures, and any known mechanism-of-action modulators. Computed by querying ChEMBL target/activity/mechanism endpoints plus a reviewed (Swiss-Prot, organism 9606) UniProt record and rolling them into a one-line tractability readout.", dataSource: "UniProt REST API (rest.uniprot.org) + ChEMBL REST API (ebi.ac.uk/chembl/api/data)", caveat: "Name-to-target resolution picks the best-ranked single human protein match and may be wrong for ambiguous names, paralogs, or complexes." },
  { id: "ligand-triage", title: "Ligand triage", what: "Ranks known active compounds for the target by combining measured potency with drug-likeness, returning a sortable table with potency, QED, Rule-of-Five violations, development phase, and SMILES. Computed from ChEMBL bioactivities (best/highest pChEMBL per molecule, restricted to IC50/Ki/Kd/EC50 at or above a chosen pChEMBL threshold, default 7) scored as 0.6*potency + 0.4*drug-likeness, where drug-likeness = 0.6*QED + 0.4*Rule-of-Five penalty.", dataSource: "ChEMBL REST API (ebi.ac.uk/chembl/api/data) — activity and molecule endpoints", caveat: "It re-uses existing public bioactivity measurements and a heuristic score, so it surfaces and ranks reported actives rather than predicting or discovering new compounds." },
  { id: "structure", title: "Structure", what: "Shows the best available 3-D receptor structure for the target in an embedded RCSB Mol* viewer, with download links and a list of alternative structures. Computed by reading PDB cross-references from the UniProt entry, ranking them by method (preferring X-ray/EM) and resolution, and falling back to an AlphaFold model link when no experimental structure is cross-referenced.", dataSource: "UniProt PDB cross-references + RCSB PDB (rcsb.org) viewer/files; AlphaFold DB (alphafold.ebi.ac.uk) as fallback", caveat: "Selection is driven by UniProt's cross-reference list and a method/resolution heuristic, so it may miss newer PDB entries and AlphaFold models are computational predictions, not experimental structures." },
  { id: "cost-benefit", title: "Cost-benefit", what: "Estimates a planning-level benefit-cost ratio, probability of approval, expected remaining cost and time, and peak/risk-adjusted revenue for a chosen modality and starting phase. Computed from published industry benchmarks (phase-by-phase likelihood-of-approval, cost, and duration) with a modality multiplier and an oncology adjustment factor of 0.65 applied to approval odds.", dataSource: "Static public benchmarks (BIO/Informa CSDR 2011-2020; Wong et al. 2019; DiMasi et al. 2016) — no live API", caveat: "This is a coarse planning heuristic built on industry-average parameters and user-supplied assumptions, not a financial valuation or a program-specific forecast." },
  { id: "literature", title: "Literature", what: "Returns recent or most-cited publications matching your search term, with title, authors, journal, year, citation count, and a DOI/Europe PMC link. Computed via a Europe PMC search sorted either by publication date (recent) or citation count (cited).", dataSource: "Europe PMC REST search API (ebi.ac.uk/europepmc/webservices/rest/search)", caveat: "Results reflect Europe PMC indexing and free-text query matching, so relevance, coverage, and citation counts depend on the query and on third-party indexing rather than expert curation." },
  { id: "pathways", title: "Pathways", what: "Lists curated human biological pathways matching your query, flagging disease pathways and linking to the Reactome detail page and interactive diagram. Computed via a clustered Reactome Content Service search restricted to Homo sapiens entries of type Pathway.", dataSource: "Reactome Content Service (reactome.org/ContentService)", caveat: "Coverage is limited to Reactome's manually curated human pathways, so a relevant pathway may be absent or only partially annotated." },
  { id: "trials", title: "Trials", what: "Returns registered clinical studies matching your search term, showing NCT ID, title, status, phase, conditions, and a direct study link. Computed via a query against the ClinicalTrials.gov v2 studies API.", dataSource: "ClinicalTrials.gov API v2 (clinicaltrials.gov/api/v2/studies)", caveat: "It reflects self-reported registry records whose status, phase, and completeness vary, and registration does not imply efficacy, safety, or approval." },
];

export const TAGLINE =
  "Trace any oncology target from druggability to clinic on open data — every figure links back to its public source.";
